### ISSUE TITLE
Build failure in `helmholtz-dirichlet.py`

### ISSUE THREAD

**Issue by person142** [inducer/pytential#1]
The demo program `helmholtz-dirichlet.py` doesn't run on my machine; I get the following traceback:

[log.txt](https://github.com/inducer/pytential/files/361714/log.txt)

The cl program that fails to build is here:

https://gist.github.com/person142/4a073c656f831d409a62759b65010768

This is on OS X 10.11.5 with boxtree, sumpy, modepy, meshmode, loopy, and PyOpenCL all built from their git master branches; everything was installed into a fresh virtualenv.

Let me know if I forgot any pertinent information, and thanks for any help.

**Comment by inducer** [comment]
I can look into this next week. I'm super-overloaded at the moment. Sorry!

**Comment by person142** [comment]
No problem; everyone's a volunteer. :-)

**Comment by inducer** [comment]
Sorry about the delay in getting back to you. What you're seeing is the Apple OpenCL compiler crashing while trying to compile one of the programs in https://github.com/inducer/boxtree. It says so itself:
```
CVMS_ERROR_COMPILER_FAILURE: CVMS compiler has crashed or hung building an element.
```
This shouldn't happen and represents a bug in software shipped by Apple. I've run into these when I put together https://github.com/pyopencl/pyopencl. Since there's no feedback beyond, they're generally a pain to debug--and I'm not likely to be much help since I don't have regular access to a Mac.

So there are two approaches to make this work:

* Work around the Apple compiler bugs. Rather than try this in the context of the layer potential FMM, we should probably check if the boxtree tests work--I'm guessing they may not. From there, we could strip the simplest failing case down until it compiles and then build it back up until it (hopefully) works.
* Use a different OpenCL implementation. Nvidia GPUs are generally fine (although I've only tried on Linux), as is [POCL](http://portablecl.org/index.html) on CPUs. POCL can also be compiled on the Mac.

Hope that helps. Let me know what you'd like to pursue.

**Comment by mattwala** [comment]
The latest version of pytential runs on macOS via miniconda and POCL (see https://gitlab.tiker.net/inducer/pytential/merge_requests/85). I think we can safely close this.

**Comment by inducer** [comment]
For anyone reading this "in the future": [These install instructions](https://documen.tician.de/pytential/misc.html#installation-and-usage) should soon update to reflect a set of instructions that work cleanly on a Mac.

**Comment by inducer** [comment]
(namely, as soon as the PR linked by @mattwala goes, in which in turn depends on https://github.com/conda-forge/pyopencl-feedstock/pull/18)
