### ISSUE TITLE
Turning on target-specific seemingly makes Stokes results worse

### ISSUE THREAD

**Issue by inducer** [inducer/pytential#11]
@alexfikl  said.

**Comment by alexfikl** [comment]
I'm playing with the Stokes tests in `test_stokes.py` and will add a PR for this soon-ish!

**Comment by alexfikl** [comment]
Turns out this was the expected false flag. 

I changed upsampling + qbx order + target specific acceleration and got the expected convergence. Just re-ran the tests more carefully and, unsurprisingly, it wasn't turning off the target specific that did the trick!

I still have a PR with some simple Stokes test cases with numbers that seem to work well, so I say we should keep this open until those are in.

**Comment by inducer** [comment]
The main puzzle (to me) is that target-specific should not affect Stokes at all. So even the fact that it did make a difference could be indicative of a bug.

**Comment by alexfikl** [comment]
Just to be clear, it didn't make any difference at all when I re-ran the tests today. 

Not quite sure what I did the first time around, but it was probably just confusion on my part from changing more than one parameter at a time..

**Comment by mattwala** [comment]
Were you using an extremely high QBX order (64-ish)? There's some fixed-size buffers in the TS implementation that would overflow if you did. That might explain a difference in the answer. There's currently no runtime checks to limit the order. It's my fault (and there's a TODO in the code to fix it).

**Comment by alexfikl** [comment]
No, no, I was using smallish orders around 4-6.

**Comment by inducer** [comment]
Closing as recommended by @alexfikl in https://github.com/inducer/pytential/issues/45#issuecomment-744074194.
